_wandb:
    value:
        cli_version: 0.21.1
        e:
            ox4a9llk9wazihc48mi7dj1d92uqwnf0:
                args:
                    - --vla_path
                    - VQ-VLA/openvla-7b-finetuned-libero-90
                    - --data_root_dir
                    - /home/work/AGI_NIH/data/embodied_features_and_demos_libero
                    - --dataset_name
                    - libero_90
                    - --run_root_dir
                    - /home/work/AGI_NIH/checkpoints/ecot_libero_finetune
                    - --adapter_tmp_dir
                    - /home/work/AGI_NIH/checkpoints/ecot_libero_finetune/lora
                    - --lora_rank
                    - "32"
                    - --max_steps
                    - "200000"
                    - --batch_size
                    - "16"
                    - --grad_accumulation_steps
                    - "1"
                    - --learning_rate
                    - "2e-5"
                    - --image_aug
                    - "False"
                    - --wandb_project
                    - ecot
                    - --wandb_entity
                    - AGI_CSI
                codePath: vla-scripts/finetune.py
                codePathLocal: vla-scripts/finetune.py
                cpu_count: 56
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "935062740992"
                        used: "647405576192"
                email: gnih1226@gmail.com
                executable: /home/work/AGI_NIH/anaconda3/envs/openvla/bin/python3.10
                git:
                    commit: 1813ad76001f1e08095088f94a86c43fc0e457a3
                    remote: https://github.com/MichalZawalski/embodied-CoT.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-f2ff4815-68e7-955a-5166-d91399cef176
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-ca1bdbf3-6aaa-2fd6-a5c5-fc2887f85a17
                host: main1
                memory:
                    total: "513248591872"
                os: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
                program: /home/work/AGI_NIH/embodied-CoT/vla-scripts/finetune.py
                python: CPython 3.10.18
                root: /home/work/AGI_NIH/embodied-CoT
                startedAt: "2025-08-11T15:16:43.603139Z"
                writerId: ox4a9llk9wazihc48mi7dj1d92uqwnf0
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 63
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 63
                - 71
                - 98
            "3":
                - 13
                - 61
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.40.1
            "12": 0.21.1
            "13": linux-x86_64
